export const argData = [
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1950",
    CropName: "CoarseCereals",
    CropProduction: 154,
    YieldOfCrops: 408,
    AreaUnderCultivation: 377,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1950",
    CropName: "Coffee",
    CropProduction: 0,
    YieldOfCrops: 0,
    AreaUnderCultivation: 0,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1950",
    CropName: "CottonLint",
    CropProduction: 30,
    YieldOfCrops: 88,
    AreaUnderCultivation: 58.8,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1950",
    CropName: "Groundnut",
    CropProduction: 35,
    YieldOfCrops: 775,
    AreaUnderCultivation: 44.9,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1950",
    CropName: "Pulses",
    CropProduction: 84,
    YieldOfCrops: 441,
    AreaUnderCultivation: 191,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1950",
    CropName: "RapeseedMustard",
    CropProduction: 8,
    YieldOfCrops: 368,
    AreaUnderCultivation: 20.7,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1950",
    CropName: "RawJuteMesta",
    CropProduction: 33,
    YieldOfCrops: 1043,
    AreaUnderCultivation: 5.7,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1950",
    CropName: "Rice",
    CropProduction: 206,
    YieldOfCrops: 668,
    AreaUnderCultivation: 308,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1950",
    CropName: "Soyabean",
    CropProduction: 0,
    YieldOfCrops: 0,
    AreaUnderCultivation: 0,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1950",
    CropName: "Sugarcane",
    CropProduction: 571,
    YieldOfCrops: 33422,
    AreaUnderCultivation: 17.1,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1950",
    CropName: "Tea",
    CropProduction: 0,
    YieldOfCrops: 0,
    AreaUnderCultivation: 0,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1950",
    CropName: "Tobacco",
    CropProduction: 3,
    YieldOfCrops: 731,
    AreaUnderCultivation: 3.6,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1950",
    CropName: "Wheat",
    CropProduction: 65,
    YieldOfCrops: 663,
    AreaUnderCultivation: 98,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1951",
    CropName: "CoarseCereals",
    CropProduction: 161,
    YieldOfCrops: 414,
    AreaUnderCultivation: 389,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1951",
    CropName: "Coffee",
    CropProduction: 0,
    YieldOfCrops: 0,
    AreaUnderCultivation: 0,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1951",
    CropName: "CottonLint",
    CropProduction: 33,
    YieldOfCrops: 85,
    AreaUnderCultivation: 65.6,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1951",
    CropName: "Groundnut",
    CropProduction: 32,
    YieldOfCrops: 649,
    AreaUnderCultivation: 49.2,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1951",
    CropName: "Pulses",
    CropProduction: 84,
    YieldOfCrops: 448,
    AreaUnderCultivation: 188,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1951",
    CropName: "RapeseedMustard",
    CropProduction: 9,
    YieldOfCrops: 393,
    AreaUnderCultivation: 24,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1951",
    CropName: "RawJuteMesta",
    CropProduction: 47,
    YieldOfCrops: 1074,
    AreaUnderCultivation: 7.9,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1951",
    CropName: "Rice",
    CropProduction: 213,
    YieldOfCrops: 714,
    AreaUnderCultivation: 298,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1951",
    CropName: "Soyabean",
    CropProduction: 0,
    YieldOfCrops: 0,
    AreaUnderCultivation: 0,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1951",
    CropName: "Sugarcane",
    CropProduction: 616,
    YieldOfCrops: 31786,
    AreaUnderCultivation: 19.4,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1951",
    CropName: "Tea",
    CropProduction: 0,
    YieldOfCrops: 0,
    AreaUnderCultivation: 0,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1951",
    CropName: "Tobacco",
    CropProduction: 2,
    YieldOfCrops: 723,
    AreaUnderCultivation: 2.9,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1951",
    CropName: "Wheat",
    CropProduction: 62,
    YieldOfCrops: 653,
    AreaUnderCultivation: 95,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1952",
    CropName: "CoarseCereals",
    CropProduction: 196,
    YieldOfCrops: 462,
    AreaUnderCultivation: 425,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1952",
    CropName: "Coffee",
    CropProduction: 0,
    YieldOfCrops: 0,
    AreaUnderCultivation: 0,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1952",
    CropName: "CottonLint",
    CropProduction: 33,
    YieldOfCrops: 89,
    AreaUnderCultivation: 63.6,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1952",
    CropName: "Groundnut",
    CropProduction: 29,
    YieldOfCrops: 611,
    AreaUnderCultivation: 48,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1952",
    CropName: "Pulses",
    CropProduction: 92,
    YieldOfCrops: 463,
    AreaUnderCultivation: 198,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1952",
    CropName: "RapeseedMustard",
    CropProduction: 9,
    YieldOfCrops: 408,
    AreaUnderCultivation: 21.1,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1952",
    CropName: "RawJuteMesta",
    CropProduction: 53,
    YieldOfCrops: 1028,
    AreaUnderCultivation: 9.3,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1952",
    CropName: "Rice",
    CropProduction: 229,
    YieldOfCrops: 764,
    AreaUnderCultivation: 300,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1952",
    CropName: "Soyabean",
    CropProduction: 0,
    YieldOfCrops: 0,
    AreaUnderCultivation: 0,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1952",
    CropName: "Sugarcane",
    CropProduction: 510,
    YieldOfCrops: 29495,
    AreaUnderCultivation: 17.3,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1952",
    CropName: "Tea",
    CropProduction: 0,
    YieldOfCrops: 0,
    AreaUnderCultivation: 0,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1952",
    CropName: "Tobacco",
    CropProduction: 3,
    YieldOfCrops: 675,
    AreaUnderCultivation: 3.6,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1952",
    CropName: "Wheat",
    CropProduction: 75,
    YieldOfCrops: 763,
    AreaUnderCultivation: 98,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1953",
    CropName: "CoarseCereals",
    CropProduction: 230,
    YieldOfCrops: 506,
    AreaUnderCultivation: 454,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1953",
    CropName: "Coffee",
    CropProduction: 0,
    YieldOfCrops: 0,
    AreaUnderCultivation: 0,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1953",
    CropName: "CottonLint",
    CropProduction: 41,
    YieldOfCrops: 100,
    AreaUnderCultivation: 69.9,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1953",
    CropName: "Groundnut",
    CropProduction: 35,
    YieldOfCrops: 811,
    AreaUnderCultivation: 42.5,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1953",
    CropName: "Pulses",
    CropProduction: 106,
    YieldOfCrops: 489,
    AreaUnderCultivation: 217,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1953",
    CropName: "RapeseedMustard",
    CropProduction: 9,
    YieldOfCrops: 389,
    AreaUnderCultivation: 22.4,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1953",
    CropName: "RawJuteMesta",
    CropProduction: 38,
    YieldOfCrops: 992,
    AreaUnderCultivation: 6.8,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1953",
    CropName: "Rice",
    CropProduction: 282,
    YieldOfCrops: 902,
    AreaUnderCultivation: 313,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1953",
    CropName: "Soyabean",
    CropProduction: 0,
    YieldOfCrops: 0,
    AreaUnderCultivation: 0,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1953",
    CropName: "Sugarcane",
    CropProduction: 444,
    YieldOfCrops: 31497,
    AreaUnderCultivation: 14.1,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1953",
    CropName: "Tea",
    CropProduction: 0,
    YieldOfCrops: 0,
    AreaUnderCultivation: 0,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1953",
    CropName: "Tobacco",
    CropProduction: 3,
    YieldOfCrops: 737,
    AreaUnderCultivation: 3.7,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1953",
    CropName: "Wheat",
    CropProduction: 80,
    YieldOfCrops: 750,
    AreaUnderCultivation: 107,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1954",
    CropName: "CoarseCereals",
    CropProduction: 228,
    YieldOfCrops: 520,
    AreaUnderCultivation: 439,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1954",
    CropName: "Coffee",
    CropProduction: 0,
    YieldOfCrops: 0,
    AreaUnderCultivation: 0,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1954",
    CropName: "CottonLint",
    CropProduction: 45,
    YieldOfCrops: 100,
    AreaUnderCultivation: 75.5,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1954",
    CropName: "Groundnut",
    CropProduction: 43,
    YieldOfCrops: 766,
    AreaUnderCultivation: 55.4,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1954",
    CropName: "Pulses",
    CropProduction: 110,
    YieldOfCrops: 500,
    AreaUnderCultivation: 219,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1954",
    CropName: "RapeseedMustard",
    CropProduction: 10,
    YieldOfCrops: 425,
    AreaUnderCultivation: 24.4,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1954",
    CropName: "RawJuteMesta",
    CropProduction: 39,
    YieldOfCrops: 1021,
    AreaUnderCultivation: 6.8,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1954",
    CropName: "Rice",
    CropProduction: 252,
    YieldOfCrops: 820,
    AreaUnderCultivation: 308,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1954",
    CropName: "Soyabean",
    CropProduction: 0,
    YieldOfCrops: 0,
    AreaUnderCultivation: 0,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1954",
    CropName: "Sugarcane",
    CropProduction: 587,
    YieldOfCrops: 36303,
    AreaUnderCultivation: 16.2,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1954",
    CropName: "Tea",
    CropProduction: 0,
    YieldOfCrops: 0,
    AreaUnderCultivation: 0,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1954",
    CropName: "Tobacco",
    CropProduction: 3,
    YieldOfCrops: 737,
    AreaUnderCultivation: 3.5,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1954",
    CropName: "Wheat",
    CropProduction: 90,
    YieldOfCrops: 803,
    AreaUnderCultivation: 113,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1955",
    CropName: "CoarseCereals",
    CropProduction: 195,
    YieldOfCrops: 449,
    AreaUnderCultivation: 435,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1955",
    CropName: "Coffee",
    CropProduction: 0,
    YieldOfCrops: 0,
    AreaUnderCultivation: 0,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1955",
    CropName: "CottonLint",
    CropProduction: 42,
    YieldOfCrops: 88,
    AreaUnderCultivation: 80.9,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1955",
    CropName: "Groundnut",
    CropProduction: 39,
    YieldOfCrops: 752,
    AreaUnderCultivation: 51.3,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1955",
    CropName: "Pulses",
    CropProduction: 110,
    YieldOfCrops: 476,
    AreaUnderCultivation: 232,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1955",
    CropName: "RapeseedMustard",
    CropProduction: 9,
    YieldOfCrops: 336,
    AreaUnderCultivation: 25.6,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1955",
    CropName: "RawJuteMesta",
    CropProduction: 54,
    YieldOfCrops: 1038,
    AreaUnderCultivation: 9.4,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1955",
    CropName: "Rice",
    CropProduction: 276,
    YieldOfCrops: 874,
    AreaUnderCultivation: 315,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1955",
    CropName: "Soyabean",
    CropProduction: 0,
    YieldOfCrops: 0,
    AreaUnderCultivation: 0,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1955",
    CropName: "Sugarcane",
    CropProduction: 605,
    YieldOfCrops: 32779,
    AreaUnderCultivation: 18.5,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1955",
    CropName: "Tea",
    CropProduction: 0,
    YieldOfCrops: 0,
    AreaUnderCultivation: 0,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1955",
    CropName: "Tobacco",
    CropProduction: 3,
    YieldOfCrops: 739,
    AreaUnderCultivation: 4.1,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1955",
    CropName: "Wheat",
    CropProduction: 88,
    YieldOfCrops: 708,
    AreaUnderCultivation: 124,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1956",
    CropName: "CoarseCereals",
    CropProduction: 199,
    YieldOfCrops: 473,
    AreaUnderCultivation: 420,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1956",
    CropName: "Coffee",
    CropProduction: 0,
    YieldOfCrops: 0,
    AreaUnderCultivation: 0,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1956",
    CropName: "CottonLint",
    CropProduction: 49,
    YieldOfCrops: 104,
    AreaUnderCultivation: 80.2,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1956",
    CropName: "Groundnut",
    CropProduction: 44,
    YieldOfCrops: 783,
    AreaUnderCultivation: 55.3,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1956",
    CropName: "Pulses",
    CropProduction: 116,
    YieldOfCrops: 495,
    AreaUnderCultivation: 233,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1956",
    CropName: "RapeseedMustard",
    CropProduction: 10,
    YieldOfCrops: 411,
    AreaUnderCultivation: 25.4,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1956",
    CropName: "RawJuteMesta",
    CropProduction: 58,
    YieldOfCrops: 977,
    AreaUnderCultivation: 10.7,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1956",
    CropName: "Rice",
    CropProduction: 290,
    YieldOfCrops: 900,
    AreaUnderCultivation: 323,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1956",
    CropName: "Soyabean",
    CropProduction: 0,
    YieldOfCrops: 0,
    AreaUnderCultivation: 0,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1956",
    CropName: "Sugarcane",
    CropProduction: 606,
    YieldOfCrops: 32979,
    AreaUnderCultivation: 18.4,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1956",
    CropName: "Tea",
    CropProduction: 0,
    YieldOfCrops: 0,
    AreaUnderCultivation: 0,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1956",
    CropName: "Tobacco",
    CropProduction: 3,
    YieldOfCrops: 739,
    AreaUnderCultivation: 4.1,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1956",
    CropName: "Wheat",
    CropProduction: 88,
    YieldOfCrops: 708,
    AreaUnderCultivation: 124,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1957",
    CropName: "CoarseCereals",
    CropProduction: 199,
    YieldOfCrops: 473,
    AreaUnderCultivation: 420,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1957",
    CropName: "Coffee",
    CropProduction: 0,
    YieldOfCrops: 0,
    AreaUnderCultivation: 0,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1957",
    CropName: "CottonLint",
    CropProduction: 49,
    YieldOfCrops: 104,
    AreaUnderCultivation: 80.2,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1957",
    CropName: "Groundnut",
    CropProduction: 44,
    YieldOfCrops: 783,
    AreaUnderCultivation: 55.3,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1957",
    CropName: "Pulses",
    CropProduction: 116,
    YieldOfCrops: 495,
    AreaUnderCultivation: 233,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1957",
    CropName: "RapeseedMustard",
    CropProduction: 10,
    YieldOfCrops: 411,
    AreaUnderCultivation: 25.4,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1957",
    CropName: "RawJuteMesta",
    CropProduction: 58,
    YieldOfCrops: 977,
    AreaUnderCultivation: 10.7,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1957",
    CropName: "Rice",
    CropProduction: 290,
    YieldOfCrops: 900,
    AreaUnderCultivation: 323,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1957",
    CropName: "Soyabean",
    CropProduction: 0,
    YieldOfCrops: 0,
    AreaUnderCultivation: 0,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1957",
    CropName: "Sugarcane",
    CropProduction: 606,
    YieldOfCrops: 32979,
    AreaUnderCultivation: 18.4,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1957",
    CropName: "Tea",
    CropProduction: 0,
    YieldOfCrops: 0,
    AreaUnderCultivation: 0,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1957",
    CropName: "Tobacco",
    CropProduction: 3,
    YieldOfCrops: 739,
    AreaUnderCultivation: 4.1,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1957",
    CropName: "Wheat",
    CropProduction: 88,
    YieldOfCrops: 708,
    AreaUnderCultivation: 124,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1958",
    CropName: "CoarseCereals",
    CropProduction: 199,
    YieldOfCrops: 473,
    AreaUnderCultivation: 420,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1958",
    CropName: "Coffee",
    CropProduction: 0,
    YieldOfCrops: 0,
    AreaUnderCultivation: 0,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1958",
    CropName: "CottonLint",
    CropProduction: 49,
    YieldOfCrops: 104,
    AreaUnderCultivation: 80.2,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1958",
    CropName: "Groundnut",
    CropProduction: 44,
    YieldOfCrops: 783,
    AreaUnderCultivation: 55.3,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1958",
    CropName: "Pulses",
    CropProduction: 116,
    YieldOfCrops: 495,
    AreaUnderCultivation: 233,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1958",
    CropName: "RapeseedMustard",
    CropProduction: 10,
    YieldOfCrops: 411,
    AreaUnderCultivation: 25.4,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1958",
    CropName: "RawJuteMesta",
    CropProduction: 58,
    YieldOfCrops: 977,
    AreaUnderCultivation: 10.7,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1958",
    CropName: "Rice",
    CropProduction: 290,
    YieldOfCrops: 900,
    AreaUnderCultivation: 323,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1958",
    CropName: "Soyabean",
    CropProduction: 0,
    YieldOfCrops: 0,
    AreaUnderCultivation: 0,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1958",
    CropName: "Sugarcane",
    CropProduction: 606,
    YieldOfCrops: 32979,
    AreaUnderCultivation: 18.4,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1958",
    CropName: "Tea",
    CropProduction: 0,
    YieldOfCrops: 0,
    AreaUnderCultivation: 0,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1958",
    CropName: "Tobacco",
    CropProduction: 3,
    YieldOfCrops: 739,
    AreaUnderCultivation: 4.1,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1958",
    CropName: "Wheat",
    CropProduction: 88,
    YieldOfCrops: 708,
    AreaUnderCultivation: 124,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1959",
    CropName: "CoarseCereals",
    CropProduction: 199,
    YieldOfCrops: 473,
    AreaUnderCultivation: 420,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1959",
    CropName: "Coffee",
    CropProduction: 0,
    YieldOfCrops: 0,
    AreaUnderCultivation: 0,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1959",
    CropName: "CottonLint",
    CropProduction: 49,
    YieldOfCrops: 104,
    AreaUnderCultivation: 80.2,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1959",
    CropName: "Groundnut",
    CropProduction: 44,
    YieldOfCrops: 783,
    AreaUnderCultivation: 55.3,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1959",
    CropName: "Pulses",
    CropProduction: 116,
    YieldOfCrops: 495,
    AreaUnderCultivation: 233,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1959",
    CropName: "RapeseedMustard",
    CropProduction: 10,
    YieldOfCrops: 411,
    AreaUnderCultivation: 25.4,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1959",
    CropName: "RawJuteMesta",
    CropProduction: 58,
    YieldOfCrops: 977,
    AreaUnderCultivation: 10.7,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1959",
    CropName: "Rice",
    CropProduction: 290,
    YieldOfCrops: 900,
    AreaUnderCultivation: 323,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1959",
    CropName: "Soyabean",
    CropProduction: 0,
    YieldOfCrops: 0,
    AreaUnderCultivation: 0,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1959",
    CropName: "Sugarcane",
    CropProduction: 606,
    YieldOfCrops: 32979,
    AreaUnderCultivation: 18.4,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1959",
    CropName: "Tea",
    CropProduction: 0,
    YieldOfCrops: 0,
    AreaUnderCultivation: 0,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1959",
    CropName: "Tobacco",
    CropProduction: 3,
    YieldOfCrops: 739,
    AreaUnderCultivation: 4.1,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1959",
    CropName: "Wheat",
    CropProduction: 88,
    YieldOfCrops: 708,
    AreaUnderCultivation: 124,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1960",
    CropName: "CoarseCereals",
    CropProduction: 199,
    YieldOfCrops: 473,
    AreaUnderCultivation: 420,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1960",
    CropName: "Coffee",
    CropProduction: 0,
    YieldOfCrops: 0,
    AreaUnderCultivation: 0,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1960",
    CropName: "CottonLint",
    CropProduction: 49,
    YieldOfCrops: 104,
    AreaUnderCultivation: 80.2,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1960",
    CropName: "Groundnut",
    CropProduction: 44,
    YieldOfCrops: 783,
    AreaUnderCultivation: 55.3,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1960",
    CropName: "Pulses",
    CropProduction: 116,
    YieldOfCrops: 495,
    AreaUnderCultivation: 233,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1960",
    CropName: "RapeseedMustard",
    CropProduction: 10,
    YieldOfCrops: 411,
    AreaUnderCultivation: 25.4,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1960",
    CropName: "RawJuteMesta",
    CropProduction: 58,
    YieldOfCrops: 977,
    AreaUnderCultivation: 10.7,
  },
  {
    Country: "India",
    Year: "Financial Year (Apr - Mar), 1960",
    CropName: "Rice",
    CropProduction: 290,
    YieldOfCrops: 900,
    AreaUnderCultivation: 323,
  },
];
